# Generated by Django 3.1.5 on 2023-06-16 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='creator',
            new_name='starter',
        ),
    ]
